baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'BrunoSphere'
theme = "hugo-theme-monochrome" 
resourceDir = "../resources/"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]
[[menu.navbar]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.navbar]]
    identifier = "about me"
    name = "About Me"
    pageRef = "_index.md"
    weight = 2

[[menu.navbar]]
    identifier = "Pictures"
    name = "Pictures"
    url = "/pictures"
    weight = 2
